extract setup and arg-parsing portion of commands

diff --git a/vcsh-functions b/vcsh-functions
--- a/vcsh-functions
+++ b/vcsh-functions
@@ -474,3 +474,79 @@ check_dir() {
 		fi
 	fi
 }
+
+setup_clone() {
+	VCSH_BRANCH=
+	if [ "$2" = -b ]; then
+		VCSH_BRANCH=$3
+		shift
+		shift
+	fi
+	[ -z "$2" ] && fatal "$VCSH_COMMAND: please specify a remote" 1
+	GIT_REMOTE="$2"
+	[ -n "$VCSH_BRANCH" ] || if [ "$3" = -b ]; then
+		VCSH_BRANCH=$4
+		shift
+		shift
+	fi
+	if [ -n "$3" ]; then
+		VCSH_REPO_NAME=$3
+		[ -z "$VCSH_BRANCH" ] && [ "$4" = -b ] && VCSH_BRANCH=$5
+	else
+		VCSH_REPO_NAME=$(basename "${GIT_REMOTE#*:}" .git)
+	fi
+	[ -z "$VCSH_REPO_NAME" ] && fatal "$VCSH_COMMAND: could not determine repository name" 1
+	export VCSH_REPO_NAME
+	[ -n "$VCSH_BRANCH" ] || VCSH_BRANCH=master
+	GIT_DIR=$VCSH_REPO_D/$VCSH_REPO_NAME.git; export GIT_DIR
+}
+
+setup_which() {
+	[ -z "$2" ] && fatal "$VCSH_COMMAND: please specify a filename" 1
+	[ -n "$3" ] && fatal "$VCSH_COMMAND: too many parameters" 1
+	VCSH_COMMAND_PARAMETER=$2; export VCSH_COMMAND_PARAMETER
+}
+
+setup_repocmd() {
+	[ -z "$2" ] && fatal "$VCSH_COMMAND: please specify repository to work on" 1
+	VCSH_REPO_NAME=$2; export VCSH_REPO_NAME
+	GIT_DIR=$VCSH_REPO_D/$VCSH_REPO_NAME.git; export GIT_DIR
+}
+
+setup_rename() {
+	[ -z "$2" ] && fatal "$VCSH_COMMAND: please specify repository to work on" 1
+	[ -z "$3" ] && fatal "$VCSH_COMMAND: please specify a target name" 1
+	VCSH_REPO_NAME=$2; export VCSH_REPO_NAME
+	GIT_DIR=$VCSH_REPO_D/$VCSH_REPO_NAME.git; export GIT_DIR
+	VCSH_REPO_NAME_NEW=$3; export VCSH_REPO_NAME_NEW;
+	GIT_DIR_NEW=$VCSH_REPO_D/$VCSH_REPO_NAME_NEW.git; export GIT_DIR_NEW
+}
+
+setup_run() {
+	[ -z "$2" ] && fatal "$VCSH_COMMAND: please specify repository to work on" 1
+	[ -z "$3" ] && fatal "$VCSH_COMMAND: please specify a command" 1
+	VCSH_REPO_NAME=$2; export VCSH_REPO_NAME
+	GIT_DIR=$VCSH_REPO_D/$VCSH_REPO_NAME.git; export GIT_DIR
+}
+
+setup_status() {
+	if [ x"$2" = x'--terse' ]; then
+		VCSH_STATUS_TERSE=1; export VCSH_STATUS_TERSE
+		shift
+	fi
+	VCSH_REPO_NAME=$2; export VCSH_REPO_NAME
+}
+
+setup_run_implicit() {
+	VCSH_COMMAND='run'; export VCSH_COMMAND
+	VCSH_REPO_NAME=$1; export VCSH_REPO_NAME
+	GIT_DIR=$VCSH_REPO_D/$VCSH_REPO_NAME.git; export GIT_DIR
+	[ -d "$GIT_DIR" ] || { help; exit 1; }
+}
+
+setup_enter_implicit() {
+	VCSH_COMMAND='enter'; export VCSH_COMMAND
+	VCSH_REPO_NAME=$1; export VCSH_REPO_NAME
+	GIT_DIR=$VCSH_REPO_D/$VCSH_REPO_NAME.git; export GIT_DIR
+	[ -d "$GIT_DIR" ] || { help; exit 1; }
+}
