move remaining function to vcsh-functions

diff --git a/vcsh-functions b/vcsh-functions
--- a/vcsh-functions
+++ b/vcsh-functions
@@ -462,3 +462,15 @@ get_full_command() {
 		*) echo "$1";;
 	esac
 }
+
+check_dir() {
+	check_directory="$1"
+	if [ ! -d "$check_directory" ]; then
+		if [ -e "$check_directory" ]; then
+			fatal "'$check_directory' exists but is not a directory" 13
+		else
+			verbose "attempting to create '$check_directory'"
+			mkdir -p "$check_directory" || fatal "could not create '$check_directory'" 50
+		fi
+	fi
+}
