simplify check_dir

diff --git a/vcsh b/vcsh
--- a/vcsh
+++ b/vcsh
@@ -516,15 +516,11 @@ normalize_cmd() {
 }
 
 check_dir() {
-	check_directory="$1"
-	if [ ! -d "$check_directory" ]; then
-		if [ -e "$check_directory" ]; then
-			fatal "'$check_directory' exists but is not a directory" 13
-		else
-			verbose "attempting to create '$check_directory'"
-			mkdir -p "$check_directory" || fatal "could not create '$check_directory'" 50
-		fi
-	fi
+	[ -d "$1" ] && return
+	[ -e "$1" ] && fatal "'$1' exists but is not a directory" 13
+
+	verbose "attempting to create '$1'"
+	mkdir -p "$1" || fatal "could not create '$1'" 50
 }
 
 check_needed_dirs() {
